{% set name = "infinite-sets" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/infinite-sets-{{ version }}.tar.gz
  sha256: 0b0120292cdabd229dd8cefc4d285b53109bc26a6fefa67dae81655ee2c6275a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - infinite_sets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://gitlab.com/alexjbinnie/infinite-sets
  summary: Code to express the universal set and set complements in a pythonic manner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alexjbinnie
